name: Build and deploy areweserveryet.org

on:
  push:
    branches:
    - main

env:
  DOMAIN_NAME: areweserveryet.org
  S3_BUCKET_NAME: areweserveryet
  S3_APEX_BUCKET_NAME: areweserveryet-apex
  S3_BUCKET_REGION: us-east-1
  FORMATION_STACK: areweserveryet-stack
  AWS_ROLE: arn:aws:iam::478978960893:role/areweserveryet-github-ci
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build site
      run: swift run
    - name: Configure AWS credentials
      id: cred
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        role-session-name: deploymain
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy to AWS Cloudformation
      id: clouddeploy
      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: ${{ env.FORMATION_STACK }}
        template: stack.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          DomainName=${{ env.DOMAIN_NAME }},
          S3BucketName=${{ env.S3_BUCKET_NAME }},
          S3ApexBucketName=${{ env.S3_APEX_BUCKET_NAME }},
          AcmCertificateArn=${{ secrets.CERTIFICATE_ARN }}
      if: steps.cred.outcome == 'success'
    - name: Deploy to S3
      id: s3deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: '${{ env.S3_BUCKET_NAME }}'
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: '${{ env.S3_BUCKET_REGION }}'
        SOURCE_DIR: 'Output'
      if: steps.clouddeploy.outcome == 'success'
    - name: Invalidate
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ steps.clouddeploy.outputs.CloudFrontID }} \
          --paths '/*'
